# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DanGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pipelineParser
import ScriptFileDC

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1920, 1080)
        Dialog.setMinimumSize(QtCore.QSize(1920, 1080))
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(300, 494, 181, 61))
        self.pushButton.setMinimumSize(QtCore.QSize(141, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.b1_clicked)
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 570, 181, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton.clicked.connect(self.b3_clicked)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(310, 90, 800, 200))
        self.label.setMinimumSize(QtCore.QSize(800, 200))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(270, 170, 800, 200))
        self.label_2.setMinimumSize(QtCore.QSize(800, 200))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(200, 290, 800, 200))
        self.label_3.setMinimumSize(QtCore.QSize(800, 200))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(490, 500, 161, 71))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(490, 560, 261, 71))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Button 1"))
        self.pushButton_3.setText(_translate("Dialog", "Button 2"))
        self.label.setText(_translate("Dialog", "Hi, Welcome to Dan\'s PyQt5 GUI"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">This script creates a Graph and Parses Genes</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Please Put Yeast Gene container under the </span></p><p><span style=\" font-size:16pt; font-weight:600;\">foldername \'YeastGenes\' to be read</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "Parser"))
        self.label_5.setText(_translate("Dialog", "Anayisis"))

    def b1_clicked(self):
        pipelineParser.main()

    def b3_clicked(self):
        ScriptFileDC.main()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
